### ISSUE TITLE
graph-node: per group env vars are affecting all groups

### ISSUE THREAD

**Issue by cjorge-graphops** [graphops/launchpad-charts#280]
When defining env vars per group, like so: 
```yaml
graphNodeGroups:
  someGroup:
    env:
      TESTENV: value
```
that env var is, in fact, showing up for all groups (and overwritting graphNodeDefaults if there exists such a var already)
