### ISSUE TITLE
heimdall: StatefulSet SEEDS env var is empty when heimdall.config.seeds overridden

### ISSUE THREAD

**Issue by johnkozan** [graphops/launchpad-charts#468]
I had to update the  `heimdall.config.seeds` value in my values.yaml file to get my heimdall node to sync.  But the SEEDS environment variable was blank in the resulting StatefulSet, resulting in heimdall config.toml not being updated with the new seeds.

values.yaml:
```yaml
  heimdall:
    config:
      seeds: "1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"
```

StatefulSet:
```yaml
          env:
            - name: SEEDS
              value:

```
